-- 테이블 생성
CREATE TABLE BBS(
	BBS_SEQ NUMBER NOT NULL,
	BBS_GROUP_NO NUMBER NOT NULL,
	BBS_REPLY_SHAPE DEFAULT '' VARCHAR2(10) NOT NULL,
    ARTICLE_SEQ NUMBER(8) PRIMARY KEY,
    USER_ID VARCHAR2(100) NOT NULL,
    TITLE VARCHAR2(255) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    READCOUNT NUMBER(8) NOT NULL,
    FILENAME VARCHAR2(200) NOT NULL,
    ORG_FILENAME VARCHAR2(200) NOT NULL,
    WDATE DATE default SYSDATE NOT NULL,
    STATUS NUMBER default 1 NOT NULL,						-- 삭제: 0, 생성: 1
    CONSTRAINT FK_MAIN_NOTICE_BBS_ID FOREIGN KEY(USER_ID)
	REFERENCES USERS(USER_ID)
);

--댓글 생성
CREATE TABLE COMMENT(
	BBS_SEQ NUMBER NOT NULL,
	COMMENT_SEQ NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(100) NOT NULL,
	COMMENT_TEXT VARCHAR2(4000) NOT NULL,
	CREATE_AT DEFAULT SYSDATE DATE NOT NULL	
)