-- 테이블 삭제
drop table COMMENTS
CASCADE CONSTRAINTS;

--테이블 생성
CREATE TABLE COMMENTS(
	BBS_SEQ NUMBER NOT NULL,
	COMMENT_GROUP_NO NUMBER NOT NULL,
	COMMENT_SHAPE VARCHAR2(10) DEFAULT '0' NOT NULL,
	COMMENT_SEQ NUMBER PRIMARY KEY,
	COMMENT_STATUS VARCHAR2(10) DEFAULT 'published' NOT NULL,
	USER_ID VARCHAR2(50) NOT NULL,
	COMMENT_CONTENT VARCHAR2(50) NOT NULL,
	COMMENT_CREATE_AT DATE DEFAULT SYSDATE NOT NULL	
);

--외래키
CONSTRAINT FK_MAIN_NOTICE_BBS_ID FOREIGN KEY(USER_ID)
REFERENCES USERS(USER_ID)

--시퀀스 생성
CREATE SEQUENCE MAIN_PDS_COMMENT_SEQ
START WITH 1 INCREMENT BY 1;

--조회
SELECT * FROM COMMENTS;