-- 테이블 삭제
drop table COMMENTS
CASCADE CONSTRAINTS;

--시퀀스 삭제
DROP SEQUENCE MAIN_PDS_COMMENT_SEQ;

--테이블 생성
CREATE TABLE COMMENTS(
	BBS_SEQ NUMBER NOT NULL,
	COMMENT_GROUP_NO NUMBER NOT NULL,
	COMMENT_SHAPE VARCHAR2(10) DEFAULT '0' NOT NULL,
	COMMENT_SEQ NUMBER PRIMARY KEY,
	COMMENT_STATUS NUMBER DEFAULT 1 NOT NULL,
	USER_ID VARCHAR2(50) NOT NULL,
	COMMENT_CONTENT VARCHAR2(50) NOT NULL,
	COMMENT_CREATE_AT DATE DEFAULT SYSDATE NOT NULL	
);

--외래키
ALTER TABLE COMMENTS
ADD CONSTRAINT FK_COMMENTS_ID FOREIGN KEY(USER_ID)
REFERENCES USERS(USER_ID);

--시퀀스 생성
CREATE SEQUENCE COMMENTS_SEQ
START WITH 1 INCREMENT BY 1;

--조회
SELECT * FROM COMMENTS;

--삭제
DELETE FROM COMMENTS;

--수정
UPDATE COMMENTS
SET COMMENT_STATUS = 1
WHERE COMMENT_SEQ = 1