DROP TABLE MAIN_NOTICE_BBS
CASCADE CONSTRAINT;

DROP SEQUENCE MAIN_NOTICE_BBS_SEQ;

CREATE TABLE MAIN_NOTICE_BBS(
    NOTICE_BBS_SEQ NUMBER(8) PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    READCOUNT NUMBER(8) NOT NULL,
    FILENAME VARCHAR2(200) NOT NULL,
    ORG_FILENAME VARCHAR2(200) NOT NULL,
    WDATE DATE NOT NULL
);

CREATE SEQUENCE NOTICE_BBS_SEQ
START WITH 1 INCREMENT BY 1;

ALTER TABLE MAIN_NOTICE_BBS
ADD CONSTRAINT FK_MAIN_NOTICE_BBS_ID FOREIGN KEY(USER_ID)
REFERENCES USERS(USER_ID);

--조회용
SELECT * FROM MAIN_NOTICE_BBS;
