-- 테이블 삭제
drop table main_pds_comment
CASCADE CONSTRAINTS;

--테이블 생성
CREATE TABLE MAIN_PDS_COMMENT(
	PDS_SEQ NUMBER NOT NULL,
	COMMENT_GROUP_NO NUMBER NOT NULL,
	COMMENT_SHAPE VARCHAR2(10) DEFAULT '' NOT NULL,
	COMMENT_SEQ NUMBER PRIMARY KEY,
	STATUS VARCHAR2(10) DEFAULT '공개' NOT NULL,
	USER_ID VARCHAR2(50) NOT NULL,
	CONTENT VARCHAR2(50) NOT NULL,
	CREATE_AT DATE DEFAULT SYSDATE NOT NULL
);

--시퀀스 생성
CREATE SEQUENCE MAIN_PDS_COMMENT_SEQ
START WITH 1 INCREMENT BY 1;