DROP TABLE MAIN_NOTICE_BBS
CASCADE CONSTRAINT;

DROP SEQUENCE MAIN_NOTICE_BBS_SEQ;

--테이블 생성
CREATE TABLE MAIN_NOTICE_BBS(
    NOTICE_BBS_SEQ NUMBER(8) PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    READCOUNT NUMBER(8) NOT NULL,
    FILENAME VARCHAR2(200) NOT NULL,
    ORG_FILENAME VARCHAR2(200) NOT NULL,
    WDATE DATE NOT NULL,
    STATUS NUMBER default 1 NOT NULL,						-- 삭제: 0, 생성: 1
    CONSTRAINT FK_MAIN_NOTICE_BBS_ID FOREIGN KEY(USER_ID)
	REFERENCES USERS(USER_ID)
);

--시퀀스 생성
CREATE SEQUENCE NOTICE_BBS_SEQ
START WITH 1 INCREMENT BY 1;

--테이블 수정
--ALTER TABLE MAIN_NOTICE_BBS ADD(STATUS NUMBER);
--UPDATE MAIN_NOTICE_BBS
--SET STATUS = 1;
--alter table MAIN_NOTICE_BBS modify STATUS not null;
--alter table MAIN_NOTICE_BBS modify (STATUS default 1);

--조회용
SELECT * FROM MAIN_NOTICE_BBS;

--페이징 조회
SELECT * 
FROM (
	SELECT NOTICE_BBS_SEQ,USER_ID,TITLE,CONTENT,READCOUNT,FILENAME,
			ORG_FILENAME,WDATE, ROW_NUMBER() OVER (ORDER BY NOTICE_BBS_SEQ desc) R
	FROM MAIN_NOTICE_BBS
	WHERE STATUS = 1
)
WHERE R BETWEEN 1 and 10;

--더미 데이터용
INSERT ALL 
	INTO MAIN_NOTICE_BBS(NOTICE_BBS_SEQ,USER_ID,TITLE,CONTENT,READCOUNT,FILENAME,ORG_FILENAME,WDATE)
	VALUES(NOTICE_BBS_SEQ.NEXTVAL, 'asdf', '더미 데이터 제목', '더미 데이터 내용', 0, '-1', '-1', SYSDATE)
SELECT * FROM DUAL;



--교수평가

학생 아이디
과목 seq
교수평가 default -1 0~

