--테이블 삭제
DROP TABLE MAIN_PDS
CASCADE CONSTRAINT;

DROP SEQUENCE PDS_SEQ;

--테이블 생성
CREATE TABLE MAIN_PDS(
    REF NUMBER(8) NOT NULL,
    reply_shape VARCHAR2(10) DEFAULT '0' NOT NULL,
    PDS_SEQ NUMBER(8) PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    READCOUNT NUMBER(8) DEFAULT 0 NOT NULL,
    FILENAME VARCHAR2(200) DEFAULT '-1' NOT NULL,
    ORG_FILENAME VARCHAR2(200) DEFAULT '-1' NOT NULL,
    STATUS NUMBER DEFAULT 1 NOT NULL,
    WDATE DATE DEFAULT SYSDATE NOT NULL
);
--외래키 생성
ALTER TABLE MAIN_PDS
ADD CONSTRAINT FK_MAIN_PDS_ID FOREIGN KEY(USER_ID)
REFERENCES USERS(USER_ID);

--시퀀스 생성
CREATE SEQUENCE PDS_SEQ
START WITH 1 INCREMENT BY 1;

--테이블 수정
--ALTER TABLE MAIN_PDS DROP COLUMN STEP
--ALTER TABLE MAIN_PDS DROP COLUMN depth
--
--ALTER TABLE MAIN_PDS ADD(reply_shape VARCHAR2(10) DEFAULT '');
--alter table MAIN_PDS modify reply_shape not null;



--조회용
SELECT * FROM MAIN_PDS;

--페이징 조회용
SELECT 
	REF, 
	reply_shape as replyShape, 
	PDS_SEQ as pdsSeq, 
	USER_ID as userId, 
	TITLE, 
	CONTENT, 
	READCOUNT, 
	FILENAME, 
	ORG_FILENAME as orgFileName, 
	STATUS, 
	WDATE
		FROM (
				select REF, reply_shape, PDS_SEQ, USER_ID, TITLE, CONTENT, READCOUNT, FILENAME, ORG_FILENAME, STATUS, WDATE,
				ROW_NUMBER() OVER (ORDER BY REF DESC, reply_shape ASC) R
				FROM MAIN_PDS
				WHERE STATUS = 1				
		)
		WHERE R BETWEEN #{startArticle} and #{endArticle}
--데이터 삭제
delete from MAIN_PDS


--더미데이터 넣기
INSERT INTO MAIN_PDS(
			REF, PDS_SEQ, USER_ID, TITLE, CONTENT, FILENAME, ORG_FILENAME
		)
		VALUES(
			PDS_SEQ.NEXTVAL, PDS_SEQ.NEXTVAL, 'asdf', 'asdf', 'asdf', '-1', '-1'
		)
		
