DROP TABLE MAIN_NOTICE_BBS
CASCADE CONSTRAINT;

DROP SEQUENCE MAIN_NOTICE_BBS_SEQ;

CREATE TABLE MAIN_NOTICE_BBS(
    NOTICE_BBS_SEQ NUMBER(8) PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    READCOUNT NUMBER(8) NOT NULL,
    FILENAME VARCHAR2(200) NOT NULL,
    ORG_FILENAME VARCHAR2(200) NOT NULL,
    WDATE DATE NOT NULL
);

--시퀀스 생성
CREATE SEQUENCE NOTICE_BBS_SEQ
START WITH 1 INCREMENT BY 1;

ALTER TABLE MAIN_NOTICE_BBS
ADD CONSTRAINT FK_MAIN_NOTICE_BBS_ID FOREIGN KEY(USER_ID)
REFERENCES USERS(USER_ID);

--조회용
SELECT * FROM MAIN_NOTICE_BBS;

--페이징 조회
SELECT * 
FROM (
	SELECT NOTICE_BBS_SEQ,USER_ID,TITLE,CONTENT,READCOUNT,FILENAME,
			ORG_FILENAME,WDATE, ROW_NUMBER() OVER (ORDER BY NOTICE_BBS_SEQ desc) R
	FROM MAIN_NOTICE_BBS
)
WHERE R BETWEEN 40 and 40;


--더미 데이터용
INSERT ALL 
	INTO MAIN_NOTICE_BBS(NOTICE_BBS_SEQ,USER_ID,TITLE,CONTENT,READCOUNT,FILENAME,ORG_FILENAME,WDATE)
	VALUES(NOTICE_BBS_SEQ.NEXTVAL, 'asdf', '더미 데이터 제목', '더미 데이터 내용', 0, '-1', '-1', SYSDATE)
SELECT * FROM DUAL;



--교수평가

학생 아이디
과목 seq
교수평가 default -1 0~

