CREATE TABLE PROFESSOR_CRITIC(
	STUDENT_ID VARCHAR2(50) NOT NULL,								--학생 ID
	SUB_SEQ NUMBER NOT NULL,									--과목 SEQ
	SCORE NUMBER DEFAULT -1 NOT NULL,							--0~10
	DEL	  NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT PROFESSOR_CRITIC_PK PRIMARY KEY(USER_ID,SUB_SEQ)	
);

DROP TABLE PROFESSOR_CRITIC
CASCADE CONSTRAINTS;

SELECT SUB_SEQ
FROM ENROLL;
SELECT SUB_SEQ
FROM SUBJECT;

SELECT E.USER_ID, S.SUB_NAME, S.USER_ID "교수"
FROM ENROLL E, SUBJECT S
WHERE E.SUB_SEQ = S.SUB_SEQ
AND E.USER_ID = 'asdf';