--학생/교수/관리자 통합 계정 정보 테이블
CREATE TABLE USERS(
    USER_ID VARCHAR2(50) PRIMARY KEY,               --SYSDATE(2017)+MAJOR_NUMBER(100)+USER_SEQ(1,2,3...)
    USER_PW VARCHAR2(50) NOT NULL,
    USER_NAME VARCHAR2(50)  NOT NULL,
    USER_EMAIL VARCHAR2(50) NOT NULL,
    USER_PHONE VARCHAR2(50) NOT NULL,
    USER_ADDRESS VARCHAR2(255) NOT NULL,
    USER_AUTH NUMBER DEFAULT 100 NOT NULL,          --학생:100,교수:200,관리자:300
    MAJOR_NUMBER NUMBER DEFAULT 0 NOT NULL,         --없음:0,기계공학과:100,전기공학과:200,컴퓨터공학과:300...
    USER_STATUS NUMBER DEFAULT 100 NOT NULL         --재학:100,휴학:200,졸업:300제적:400
);

-- USER_ID 생성용 시퀀스
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1; 

-- 조회용
SELECT * FROM USERS;